apiVersion: v2
name: monitoring-umbrella
version: 0.1.0
dependencies:
  - name: k8s-monitoring
    version: 2.1.3
    repository: https://grafana.github.io/helm-charts
  - name: loki
    version: 6.30.0
    repository: https://grafana.github.io/helm-charts
  - name: grafana-operator
    version: v5.18.0
    repository: https://grafana.github.io/helm-charts
