argo-cd:
  global:
    domain: argocd.computas.cloud

    networkPolicy:
      create: true

  configs:
    repositories:
      argocd:
        url: https://github.com/baksetercx/whpah.git

    dex:
      enabled: false

    params:
      server.insecure: true
