apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-tls
  namespace: argocd
spec:
  secretName: ingress-tls
  dnsNames:
    - argocd.computas.cloud
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
